name: Danger
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
  workflow_call:

jobs:
  danger:
    uses: numbata/ruby-grape-danger/.github/workflows/danger-run.yml@report-workflows
    secrets: inherit
